// my-vue-contacts/src/Contacts.vue
<script setup>
    import { ref, onMounted } from "vue";
    import axios from "axios";
    
    // reactive state
    const contacts = ref([]);
    const formData = ref({
        name: "",
        email: "",
        message: ""
    });

    async function loadContacts() {
        try {
            const res = await axios.get("/api/contacts/");
            contacts.value = res.data;
        } catch (err) {
            console.error(err);
        }
    }

    onMounted(() => {
        loadContacts();
    });

    async function handleSubmit() {
        try {
            await axios.post("/api/contacts/", formData.value);
            formData.value = {name: "", email: "", message: ""};
            loadContacts();
        } catch (err) {
            console.error(err);
        }
    }
</script>

<template>
    <div style="max-width:500px; margin:0 auto;">
        <h2>Contact Form</h2>
        <form @submit.prevent="handleSubmit">
            <input v-model="formData.name" placeholder="Name" required /><br /><br />
            <input v-model="formData.email" type="email" placeholder="Email" required /><br /><br />
            <textarea v-model="formData.message" placeholder="Message" required></textarea>
            <button type="submit">Submit</button>
        </form>

        <h2>Saved Contacts</h2>
        <ul>
            <li v-for="c in contacts" :key="c.id">
                {{ c.name }} ({{ c.email }}): {{ c.message }}
            </li>
        </ul>
    </div>
</template>

// react-contacts/src/Contacts.js
import React, { useState, useEffect } from "react";
import axios from "axios";

function Contacts() {
    const [contacts, setContacts] = useState([]);
    const [formData, setFormData] = useState({
        name: "",
        email: "",
        message: ""
    });

    const loadContacts = async () => {
        try {
            const res = await axios.get("/api/contacts/");
            setContacts(res.data);
        } catch (err) {
            console.error(err);
        }
    };

    useEffect(() => {
        loadContacts();
    }, []);

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            await axios.post("/api/contacts/", formData);
            setFormData({ name: "", email: "", message: ""});
            loadContacts();
        } catch (err) {
            console.error(err);
        }
    };

    return (
        <div style={{ maxWidth: "500px", margin: "0 auto" }}>
            <h2>Contact Form</h2>
            <form onSubmit={handleSubmit}>
                <input
                    type="text" 
                    name="name"
                    placeholder="Name"
                    value={formData.name}
                    onChange={handleChange}
                    required
                /><br /><br />
                <input
                    type="email" 
                    name="email"
                    placeholder="Email"
                    value={formData.email}
                    onChange={handleChange}
                    required
                /><br /><br />
                <textarea
                    name="message"
                    placeholder="Message"
                    value={formData.message}
                    onChange={handleChange}
                    required
                ></textarea><br /><br />
                <button type="submit">Submit</button>
            </form>

            <h2>Saved Contacts</h2>
            <ul>
                {contacts.map((c) => (

                    <li key={c.id}>
                        {c.name} ({c.email}): {c.message}
                    </li>
                ))}
            </ul>
        </div>
    );
}

export default Contacts;
